services:
  main-db:
    image: postgres:16.1
    container_name: main-db-container
    volumes:
      - main_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    volumes:
      - stats_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SERVER_PORT: 9090

  main-service:
    build: ./main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/explorewithme
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      STATS_SERVICE_URL: http://stats-server:9090
      SERVER_PORT: 8080
    restart: on-failure

volumes:
  main_db_data:
  stats_db_data: